export const copy = {
  en: {
    invitation: 'THE WEDDING INVITATION', details: 'The details', moments: 'Our moments', rsvp: 'Confirm attendance',
    skip: 'Skip to wedding details', backToTop: 'New & Sai, back to top', language: 'Language', switchThai: 'Switch to Thai', switchEnglish: 'Switch to English', dayInfo: 'Wedding day information',
    dear: 'DEAR', intro: 'We would love to celebrate with you.', intro2: 'Let us know how many of you will join us.',
    confirmedGuests: 'guests confirmed', replySaved: 'Your reply is saved', quickReply: 'A little reply. A big help for our day.', ownerView: 'Guest list',
    invite: 'Join us for our wedding', invite2: 'and an evening with friends and family.',
    scroll: 'A DAY TO REMEMBER', day: 'SATURDAY', month: 'NOVEMBER', year: '2026', city: 'BANGKOK, THAILAND',
    celebration: '01 — THE CELEBRATION', celebrationTitle: 'The date.', celebrationItalic: 'The place.',
    venueCopy: 'Together in a beautiful place, surrounded by our favourite people. We can’t wait to share this day with you.',
    dateLabel: 'THE DATE', dateFull: 'Saturday, 21 November 2026', timeLabel: 'THE TIME', timeFull: 'Family blessing at 16:00',
    placeLabel: 'THE PLACE', directions: 'Get directions', calendar: 'Add to calendar',
    schedule: '02 — THE ORDER OF THE DAY', scheduleTitle: 'Here’s the plan.',
    dress: 'Dress Code', dressCopy: 'Soft, bright colors',
    gallery: '04 — THE LITTLE THINGS', galleryTitle: 'Us, in the in-between.',
    photoLabel: 'NEW & SAI', giftTitle: 'Your presence', giftItalic: 'is the greatest gift.',
    giftCopy: 'Thanks for celebrating with us.',
    replyTitle: 'Will you join us?', replyCopy: 'Let us know how many people will join you so we can plan the food and seating.', replyBy: 'Kindly reply by', headcountNote: 'Tell us how many will join you',
    withLove: 'SEE YOU THERE', questions: 'A little question?', contact: 'Get in touch', share: 'Share invitation', copied: 'Invitation link copied', copyLink: 'Copy the link below',
    accept: 'I’ll be there', decline: 'Can’t make it', rsvpSubtitle: 'Tell us how many people are coming.', attending: 'Number of guests', optional: 'optional',
    dietary: 'Dietary requirements', dietaryPlaceholder: 'Allergies, vegetarian, or anything we should know', submit: 'Send my reply', saving: 'Sending your reply…',
    success: 'SEE YOU THERE', successCopy: 'Your reply is saved. See you at the wedding!', declineTitle: 'REPLY SAVED', declineCopy: 'Thanks for letting us know.',
    edit: 'Edit your reply', close: 'Close', done: 'Lovely, thank you', error: 'We couldn’t save your reply. Please try again.',
    demo: 'Design preview · Your reply is saved only in this browser.',
    today: 'TODAY', tomorrow: 'TOMORROW', begins: 'Family blessing begins at 16:00', yourTable: 'YOUR TABLE', table: 'TABLE',
    shareNote: 'This link is personal to your invitation. Share it only with the people invited with you.', shareTitle: 'The wedding of New & Sai', invitationUrl: 'Invitation URL',
    saturday: 'Saturday, the twenty-first of November'
  },
  th: {
    invitation: 'คำเชิญร่วมงานแต่งงาน', details: 'รายละเอียด', moments: 'ภาพความทรงจำ', rsvp: 'ยืนยันการเข้าร่วม',
    skip: 'ข้ามไปยังรายละเอียดงานแต่งงาน', backToTop: 'New & Sai กลับไปด้านบน', language: 'ภาษา', switchThai: 'เปลี่ยนเป็นภาษาไทย', switchEnglish: 'เปลี่ยนเป็นภาษาอังกฤษ', dayInfo: 'ข้อมูลวันแต่งงาน',
    dear: 'เรียน', intro: 'เราอยากร่วมฉลองวันพิเศษนี้กับคุณ', intro2: 'กรุณาแจ้งจำนวนคนที่จะมาร่วมงานกับเรา',
    confirmedGuests: 'คนที่ยืนยันเข้าร่วม', replySaved: 'บันทึกคำตอบของคุณแล้ว', quickReply: 'คำตอบของคุณช่วยให้เราเตรียมวันพิเศษได้อย่างอบอุ่น', ownerView: 'รายชื่อแขก',
    invite: 'เราสองคนและครอบครัว ขอเรียนเชิญคุณร่วมฉลอง', invite2: 'งานแต่งงานของเรา',
    scroll: 'วันแห่งความทรงจำ', day: 'วันเสาร์', month: 'พฤศจิกายน', year: '2569', city: 'กรุงเทพมหานคร ประเทศไทย',
    celebration: '01 — งานฉลองของเรา', celebrationTitle: 'วัน เวลา', celebrationItalic: 'และสถานที่',
    venueCopy: 'ร่วมกันในสถานที่แสนอบอุ่น ท่ามกลางคนที่เรารัก เรารอที่จะได้แบ่งปันวันพิเศษนี้กับคุณ',
    dateLabel: 'วันที่', dateFull: 'วันเสาร์ที่ 21 พฤศจิกายน 2569', timeLabel: 'เวลา', timeFull: 'พิธีรับไหว้เริ่ม 16:00 น.',
    placeLabel: 'สถานที่', directions: 'ดูเส้นทาง', calendar: 'เพิ่มในปฏิทิน',
    schedule: '02 — กำหนดการ', scheduleTitle: 'กำหนดการในวันงาน',
    dress: 'Dress Code', dressCopy: 'โทนสีอ่อนสดใส',
    gallery: '04 — เรื่องราวเล็ก ๆ', galleryTitle: 'ความสุขระหว่างทาง',
    photoLabel: 'New & Sai', giftTitle: 'การมาร่วมงานของคุณ', giftItalic: 'คือของขวัญที่ดีที่สุด',
    giftCopy: 'ขอบคุณที่มาร่วมฉลองกับเรานะคะ',
    replyTitle: 'มาร่วมฉลองกันนะคะ', replyCopy: 'แจ้งจำนวนคนที่จะมาร่วมงานได้เลย เราจะได้เตรียมอาหารและที่นั่งให้พร้อม', replyBy: 'กรุณาตอบรับภายใน', headcountNote: 'แจ้งจำนวนคนที่จะมาร่วมงาน',
    withLove: 'แล้วเจอกันนะ', questions: 'มีคำถามไหมคะ', contact: 'ติดต่อเรา', share: 'แชร์คำเชิญ', copied: 'คัดลอกลิงก์แล้ว', copyLink: 'คัดลอกลิงก์ด้านล่าง',
    accept: 'ยินดีเข้าร่วม', decline: 'ไม่สะดวกเข้าร่วม', rsvpSubtitle: 'แจ้งจำนวนคนที่จะมาร่วมงานได้เลย', attending: 'จำนวนผู้เข้าร่วม', optional: 'ไม่บังคับ',
    dietary: 'ข้อจำกัดด้านอาหาร', dietaryPlaceholder: 'อาหารที่แพ้ มังสวิรัติ หรือข้อมูลที่อยากให้เราทราบ', submit: 'ส่งคำตอบ', saving: 'กำลังส่งคำตอบ…',
    success: 'แล้วพบกันนะคะ', successCopy: 'บันทึกคำตอบแล้ว แล้วเจอกันในงานนะคะ', declineTitle: 'บันทึกคำตอบแล้ว', declineCopy: 'ขอบคุณที่แจ้งให้เราทราบนะคะ',
    edit: 'แก้ไขคำตอบ', close: 'ปิด', done: 'ขอบคุณค่ะ', error: 'ไม่สามารถบันทึกได้ กรุณาลองอีกครั้ง',
    demo: 'ตัวอย่างดีไซน์ · คำตอบบันทึกเฉพาะในเบราว์เซอร์นี้',
    today: 'วันนี้', tomorrow: 'พรุ่งนี้', begins: 'พิธีรับไหว้เริ่มเวลา 16:00 น.', yourTable: 'โต๊ะของคุณ', table: 'โต๊ะ',
    shareNote: 'ลิงก์นี้เป็นคำเชิญส่วนตัว กรุณาแชร์เฉพาะผู้ที่ได้รับเชิญร่วมกับคุณ', shareTitle: 'งานแต่งงานของ New & Sai', invitationUrl: 'ลิงก์คำเชิญ',
    saturday: 'วันเสาร์ที่ยี่สิบเอ็ด พฤศจิกายน'
  }
};
